server:
  port: 9001


spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.3:1111 #nacos 集群
        #server-addr: localhost:8848  #单机版
management:
  endpoints:
    web:
      exposure:
        include: '*'