
server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.i520java.springcloud.entities



eureka:
  client:
    register-with-eureka: true #是否将自己本身注册到注册中心中
    fetch-registry: true  #false表示当前本身就是注册中心 职责是维护实例 不做检索服务
    serviceUrl:
      ## defaultZone: http://localhost:7001/eureka  # 单击版本
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群注册

  instance:
    instance-id: paymentHtstrix8001 #修改服务名称 ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true # 访问路径显示IP


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


